/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ladyt.form;

import employee_connectivity.connection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lady T
 */
public class employee_Attendance extends javax.swing.JPanel {
     DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form employee_Attendance
     */
    public employee_Attendance() {
        initComponents();
        
    }
    
     public employee_Attendance(String em) {
        initComponents();
        jLabel1.setText(em);
        jLabel1.setVisible(false);
          view();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "EMPLOYEE ID", "FULL NAME", "EMAIL ADDRESS", "STATUS", "ATTENDANCE DATE"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(new java.awt.Color(56, 138, 112));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void view() {
        String emp = jLabel1.getText();
         jScrollPane1.getViewport().remove(jTable1);
        model = (DefaultTableModel) jTable1.getModel();
        String[] ColumnName = {"FULL NAME", "EMPLOYEE EMAIL","STATUS", "ATTENDANCE DATE"};
                   
       String[][] data;
        int Total = 0;
        String viewAllCont = "Select * from attendance where employeeId = '"+emp+"';";
        try {
                    connection cconnection = new connection();
                    Connection conn = cconnection.getConnection();
               
            Statement stat = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet result = stat.executeQuery(viewAllCont);
            

            int i = 0;
            result.afterLast();
            if (result.previous()) {
                Total = result.getRow();
            }
            result.beforeFirst();
            data = new String[Total][4];
            if (Total != 0) {
                while (result.next()) {
         
                    data[i][0] = result.getString("employeeFullName");
                    data[i][1] = result.getString("employeeEmail");
                    data[i][2] = result.getString("status");
                    data[i][3] = result.getString("attendance_date");
                                
                    i++;

                }
                  
            } else {
                data[i][0] = null;
                data[i][1] = null;
                data[i][2] = null;
                data[i][3] = null;
              
            }
            jTable1 = new JTable(data,ColumnName);
            jTable1.setFillsViewportHeight(true);
             jTable1.setEnabled(false);
            jScrollPane1.getViewport().add(jTable1);
             conn.close();
        }
        
            catch(SQLException e){
        }
           
    }

}
