package com.ladyt.form;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.ladyt.menu.EventMenu;
import com.ladyt.menu.MainForm;
import com.ladyt.menu.MenuItem;
import java.awt.Component;
import java.awt.Toolkit;





/**
 *
 * @author raven
 */
public class employeeMain extends javax.swing.JFrame {
    private MainForm main;
    /**
     * Creates new form Main
     */
   public employeeMain() {
        initComponents();
       
  
   }
   
   public employeeMain(String usp){
        initComponents();
        jLabel2.setText(usp);
          FlatAnimatedLafChange.showSnapshot();
         FlatDarculaLaf.setup();
         FlatLaf.updateUI();
         FlatAnimatedLafChange.hideSnapshotWithAnimation();
        
         String em = jLabel2.getText();
        setLogo();
        menu1.addEventMenuSelected(new EventMenu(){
            @Override
            public void mainMenuSelected(MainForm mainForm, int index, MenuItem menuItem) {
                
            }

            @Override
            public void subMenuSelected(MainForm mainForm, int index, int subMenuIndex, Component menuItem) {
                if (index == 0) {
                    if (subMenuIndex == 0) {              
                      mainForm.displayForm(new employee_Attendance(em));               
                    } 
                    
                }
              
                 if (index == 1) {
                    if (subMenuIndex == 0) {
                      mainForm.displayForm(new employeeLeaveRequest(em));               
                    } 
                    else if (subMenuIndex == 1) {             
                        mainForm.displayForm(new employeeResponse(em));
                    }  
                     
                }
                 
                 if (index == 2) {
                    if (subMenuIndex == 0) {
                      mainForm.displayForm(new employeePaidSalary(em));               
                    } 

                }
                  if (index == 3) {
                    if (subMenuIndex == 0) {
                      mainForm.displayForm(new employeeLogout(em));               
                    } 

                }

            }
            
        });
        menu1.setSelectedIndex(0);
                
    }

    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new com.ladyt.menu.Menu();
        jLabel1 = new javax.swing.JLabel();
        menuItem1 = new com.ladyt.menu.MenuItem();
        menuItem2 = new com.ladyt.menu.MenuItem();
        menuItem4 = new com.ladyt.menu.MenuItem();
        menuItem5 = new com.ladyt.menu.MenuItem();
        subMenuPanel1 = new com.ladyt.menu.SubMenuPanel();
        mainForm = new com.ladyt.menu.MainForm();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Page");

        menu1.setMainForm(mainForm);
        menu1.setSubMenuPanel(subMenuPanel1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ladyt/form/logo_1.png"))); // NOI18N
        menu1.add(jLabel1);

        menuItem1.setForeground(new java.awt.Color(72, 230, 114));
        menuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ladyt/icon/im3 - Copy.png"))); // NOI18N
        menuItem1.setText("menuItem1");
        menuItem1.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "com/ladyt/icon/im3.png", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem1.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Attendance" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem1MouseClicked(evt);
            }
        });
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        menu1.add(menuItem1);

        menuItem2.setForeground(new java.awt.Color(204, 255, 0));
        menuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ladyt/icon/im5 - Copy.png"))); // NOI18N
        menuItem2.setText("menuItem2");
        menuItem2.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "com/ladyt/icon/im9.png", "com/ladyt/icon/im4.png", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem2.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Request Leave", "Leave Response" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu1.add(menuItem2);

        menuItem4.setForeground(new java.awt.Color(0, 255, 0));
        menuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ladyt/icon/im6 - Copy.png"))); // NOI18N
        menuItem4.setText("menuItem4");
        menuItem4.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "com/ladyt/icon/im6.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem4.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Payment Info" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu1.add(menuItem4);

        menuItem5.setForeground(new java.awt.Color(255, 0, 0));
        menuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ladyt/icon/logout.png"))); // NOI18N
        menuItem5.setText("menuItem5");
        menuItem5.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "com/ladyt/icon/logout - Copy.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem5.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Logout" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu1.add(menuItem5);

        subMenuPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 1, 1, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        mainForm.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(subMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainForm, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addComponent(subMenuPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuItem1ActionPerformed
        // TODO add your handling code here:
    
    
    }//GEN-LAST:event_mainMenuItem1ActionPerformed

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        // TODO add your handling code here:
      
           
    }//GEN-LAST:event_menuItem1ActionPerformed

    private void menuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem1MouseClicked

    public static void main(String args[]) {
        FlatLaf.registerCustomDefaultsSource("com.ladyt.style");
        FlatIntelliJLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private com.ladyt.menu.MainForm mainForm;
    private com.ladyt.menu.Menu menu1;
    private com.ladyt.menu.MenuItem menuItem1;
    private com.ladyt.menu.MenuItem menuItem2;
    private com.ladyt.menu.MenuItem menuItem4;
    private com.ladyt.menu.MenuItem menuItem5;
    private com.ladyt.menu.SubMenuPanel subMenuPanel1;
    // End of variables declaration//GEN-END:variables

    private void setLogo() {
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo_1.png")));
    }

}
