/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ladyt.form;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import employee_connectivity.connection;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import notification.Notification;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author Lady T
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form adminLogin
     */
    public Login() {
        initComponents();
         setResizable(false);
             Dimension newcontact = this.getSize();
        Dimension myscreen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((myscreen.width-newcontact.width)/2,(myscreen.height
                - newcontact.height)/10);
              FlatAnimatedLafChange.showSnapshot();
         FlatDarculaLaf.setup();
         FlatLaf.updateUI();
         FlatAnimatedLafChange.hideSnapshotWithAnimation();
        
        setLogo();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        loginAdmin();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loginEmployee();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void loginAdmin() {
    String us = jTextField1.getText();
    String pass = jPasswordField1.getText();
    if(us.length()>0){
    if(pass.length()>0){
    connection cconnection = new connection();
    try (java.sql.Connection conn = cconnection.getConnection()) {
             Statement stati = conn.createStatement();
    String sele = "SELECT * From admin;";
    ResultSet res = stati.executeQuery(sele);
     while(res.next()){
    String adm = res.getString("username");
    String pas = res.getString("password");
    if((adm.compareTo(us)==0)){
    if((pas.compareTo(pass)==0)){
        
      new adminMain().setVisible(true);
 
    System.out.println("SeenNow");      
          this.dispose();

     }else{

    Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Incorrect Password");
                   panel.showNotification();
                  

    jPasswordField1.setText(null);
     }

    }else{
    
      Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Incorrect Username");
                      panel.showNotification();
                      this.getFrame().dispose();
      jTextField1.setText(null);
    }
   
    }
       conn.close();
    }catch(Exception ex){
    }
    }else{
      Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Enter your Password");
                   panel.showNotification();

       }
    }else{
       Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Enter your Username");
                   panel.showNotification();

    }
    }
    
     protected JFrame getFrame() {
	for (Container p = getParent(); p != null; p = p.getParent()) {
	    if (p instanceof JFrame) {
		return (JFrame) p;
	    }
	}
	return null;
    }

    private void loginEmployee() {
    String usu = jTextField1.getText();
    String passu = jPasswordField1.getText();
    if(usu.length()>0){
    if(passu.length()>0){
    connection cconnection = new connection();
    try (java.sql.Connection conn = cconnection.getConnection()) {
             Statement stati = conn.createStatement();
    String sele = "SELECT * From employeelogindetails where employeeId = '"+usu+"';";
    ResultSet ress = stati.executeQuery(sele);
     while(ress.next()){
         
    String admm = ress.getString("employeeId");
    String pasm = ress.getString("password");
     
    if((admm.compareTo(usu)==0)){
    if((pasm.compareTo(passu)==0)){
        
      String usp = jTextField1.getText();
      new employeeMain(usp).setVisible(true);
        String update =  " UPDATE employeelogindetails SET status ='Logged In' where employeeId = '"+usp+"';";
            stati.executeUpdate(update);   
        this.dispose();

     }else{

    Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Incorrect Password");
                   panel.showNotification();
                   

    jPasswordField1.setText(null);
     }

    }else{
    
      Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Incorrect Username");
                      panel.showNotification();
                     
                      this.getFrame().dispose();
                      
      jTextField1.setText(null);
    }
   
    }
      conn.close();
    }catch(Exception ex){
    }
    }else{
      Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Enter your Password");
                   panel.showNotification();

       }
    }else{
       Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Enter your Username");
                   panel.showNotification();

    }
    }

     private void setLogo() {
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo_1.png")));
    }
}
